[tool.poetry]
name = "pydra-bids"
version = "0.0.1"
description = "Pydra Tasks for BIDS"
authors = ["The Aramis Lab"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"
pydra = "^0.19"
ancpbids = {git = "https://github.com/ANCPLabOldenburg/ancp-bids", rev = "be3f0faf1412e65467e13864dd6890662b4b36f2"}

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
isort = "^5.10.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
Sphinx = "^5"
numpydoc = "^1.4"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
  "--doctest-modules",
  "--doctest-continue-on-failure",
]

[tool.black]
target-version = ["py37"]

[tool.isort]
py_version = 37
profile = "black"
