name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
          cache: poetry
      - name: Install dependencies
        run: make install-docs
      - name: Build documentation
        run: make docs
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10'
          cache: poetry
      - name: Install dependencies
        run: make install
      - name: Lint code
        run: make lint
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make test
